version: '3.8'

services:
  web:
    build: .
    command: gunicorn website.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./API/website:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - API/website/.env.production
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - API/website/.env.production

volumes:
  postgres_data: